### ISSUE TITLE
High-Level Code Reorg

### ISSUE THREAD

**Issue by john-science** [theJollySin/wanderlust#9]
I need to organize this project a bit more. Something like:

    Web UI
    Game Engine
        ROT.js Interface
        Save / Load Interface
    In-Game Universe mechanics
        Astronomy
        Sun
        Player (including health and inventory)
        Meteorology
        Data Loader(s)

**Comment by theJollySin** [comment]
I need to organize this project a bit more.  Something like:

- Web UI
- Game Engine
  - ROT.js Interface
  - Save / Load Interface
- In-Game Universe mechanics
  - Astronomy
  - Sun
  - Player (including health and inventory)
  - Meteorology
  - Data Loader(s)

**Comment by john-science** [comment]
No, the code base isn't that big. I don't mind a flat layout.
